version: '3'
services:

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=medcal"
      - "MYSQL_USER=medcal"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "3306:3306"
volumes:
  dbdata:
